### ISSUE TITLE
Typescript isnt supported?

### ISSUE THREAD

**Issue by ImLunaHey** [vovikhangcdv/codeql-agent#3]
If I set typescript as the language I get this error. The README states typescript is supported though.

```
The language are not supported. Support language list: cpp, csharp, go, java, javascript, python, ruby
```

**Comment by doublevkay** [comment]
You have to specify [`javascript` for Javascript/Typescript](https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/#running-codeql-database-create) codebases, and CodeQL will do the rest.
